name: "GitHub-registry-CI-CD"

on:
  push:
    branches:
      - dev
env:
  TAG: ${{ github.sha }}

jobs:
  my-docker:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        
      - name: "Login GitHub registry"
        run: docker login ghcr.io -u sivin79 --password "${{ secrets.CR_PAT }}"

      - name: "Build"
        run: docker build -t ghcr.io/sivin79/push_gh_registry:${{ env.TAG }} .
        
      - name: "Push"
        run: docker push ghcr.io/sivin79/push_gh_registry:${{ env.TAG }}
