name: "GitHub-registry-CI-CD"

on:
  push:
    branches:
      - main

env:
  HASH: ${{ github.sha }}

jobs:
  my-docker:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        
      - name: "login github registry"
        run: docker login ghcr.io -u sivin79 --password "${{ secrets.CR_PAT}}"

      - name: "Build"
        run: docker build -t ghcr.io/sivin79/push_gh_registry:1.0.1 .
        
      - name: "Push"
        run: docker push ghcr.io/sivin79/push_gh_registry:1.0.1
